//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelAgency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationT
    {
        public int reservationid { get; set; }
        public Nullable<int> reservationnumber { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> tourid { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> hotelid { get; set; }
    
        public virtual CustomerT CustomerT { get; set; }
        public virtual HotelT HotelT { get; set; }
        public virtual TourT TourT { get; set; }
    }
}
